### ISSUE TITLE
Suggestion: to use landscape.io health code

### ISSUE THREAD

**Issue by necrostylery** [Runscope/healthcheck#14]
Hi, I recently started to use landscape.io service to analyse my python codes and I recommend to use on this open source project, because is 100% free for open source projects.

I put my fork project to be analysed and I found some issues (styles, pep8, warnings) and I will submit a pull request with these improvements (previously health 74%, actual 90%).

Landscape.io provides a badge to be put in the README for realtime analysis.

So, if you have any interest to improve this project, I think this is a good way.

**Comment by johnsheehan** [comment]
Thanks for running the analysis and submitting the PR! :smile: 

Ongoing, I think it's a bit more than is needed for this project though. If we decide to add something like this, it will probably be Code Climate.
