### ISSUE TITLE
EnvironmentDump breaks in Python3

### ISSUE THREAD

**Issue by lobobabysaurus** [Runscope/healthcheck#21]
line 159 of healtcheck/__init__.py in dump_environment there is a call to self.functions.iteritems():

Python 3 does not support iteritems on dicts, which breaks the ability to actually do an environment dump if using Python 3

**Comment by lobobabysaurus** [comment]
Added https://github.com/Runscope/healthcheck/pull/22 as a potential fix

**Comment by tomas-fp** [comment]
Same issue here! Do you want a PR?

**Comment by psimmons-vistar** [comment]
@tomas-fp #23 is a PR for it using the six library.  It just hasn't ever been reviewd

**Comment by frankstratton** [comment]
just saw this, sorry it took so long to get to it!

**Comment by lobobabysaurus** [comment]
Thanks @frankstratton!
