### ISSUE TITLE
python3 support 

### ISSUE THREAD

**Issue by drorasaf** [Runscope/healthcheck#26]
Currently the pip install provides the 1.3.1 which does not include the latest fix with six.iteritems for python 3.
Could you please update pypi with a new package?

Thanks!
Great work on this project:)

**Comment by DuncanBetts** [comment]
Hi, I'm running cp35, found your project today. Looks great 👍, I'd like to incorporate it into a project I'm working on, so am seconding the above.

In the meantime I believe this line in requirements.txt will work (leaving this here for anyone who needs it):
-e git://github.com/Runscope/healthcheck.git@9d304f2b1923515cdf154d6f351f6ab7805f85da

**Comment by holmars** [comment]
It would be great to get a new release that includes the py3 fix. Thanks!

**Comment by luiscoms** [comment]
Hi, my fork [py-healthckeck](https://pypi.python.org/pypi/py-healthcheck) supports python 3

**Comment by jab** [comment]
This can be closed, as per https://github.com/Runscope/healthcheck/blob/master/CHANGELOG.md#120
> ## 1.2.0
> Adds support for Python 3.x.
