### ISSUE TITLE
Pip 10.0 breaks Environment Dump

### ISSUE THREAD

**Issue by buddah3243** [Runscope/healthcheck#33]
Pip 10.0 moves the location of pip.get_installed_distributions() and use of this function is not supported by the pip team

probably should use pkg_resources.working_set instead

**Comment by tusharmakkar08** [comment]
@buddah3243: For temporary fix you can use `pip install pip==9.0.1 `

**Comment by frankstratton** [comment]
Feel free to open a pull request with the fix

**Comment by tusharmakkar08** [comment]
Opened a PR for the same.
