### ISSUE TITLE
Releasing of new version on Pypi

### ISSUE THREAD

**Issue by tusharmakkar08** [Runscope/healthcheck#35]
Hey @frankstratton 

Can we release a new version with the fix for issue https://github.com/Runscope/healthcheck/issues/33 ? 

Thanks

**Comment by frankstratton** [comment]
yes, i will release later today. thanks!

**Comment by tusharmakkar08** [comment]
Thanks :D

**Comment by tusharmakkar08** [comment]
I see the new version has been released. Thanks. Closing the issue.
